### ISSUE TITLE
Useless

### ISSUE THREAD

**Issue by dedg3** [abecodes/hasher64#2]
Its just nodes std buffer api 🤷🏻‍♂️ Srsly?

**Comment by abecodes** [comment]
Nice to hear from you, hope you are well in these daring times.

It was part of an tutorial post, here you can read up the [full article](https://medium.com/@abecodes/creating-and-publishing-a-npm-package-1fe82249e530)

Stay at home and healthy, always happy to get a live sign from you :tada:
